# Generated by Django 3.0.5 on 2020-05-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desription', models.TextField()),
                ('detail', models.TextField()),
                ('image', models.FileField(upload_to='static/images')),
                ('requirements', models.TextField()),
                ('domain', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('categories', models.ManyToManyField(to='portfolio.Category')),
            ],
        ),
    ]
