# Generated by Django 3.0.5 on 2020-05-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='images/project'),
        ),
    ]
