# Generated by Django 3.0.5 on 2020-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200503_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='Mr. Client', max_length=20),
            preserve_default=False,
        ),
    ]
